---
sudo: false
language: ruby
bundler_args: --without development
before_install:
  - rm Gemfile.lock || true
  - gem update bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.8.1" STRICT_VARIABLES=yes
